name: Build

on:
  workflow_dispatch:  

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run build shell script
        run: |
            bash build.sh
      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: armeabi-v7a-binary
          path: build/releases/armeabi-v7a/libnative-lib.so
